#!/usr/bin/env python

import json
from os import getenv
import requests
from sys import argv


GITHUB_TOKEN = getenv('GITHUB_TOKEN')
webhook = getenv('SLACK_WEBHOOK')

repo = argv[1]
if webhook is None:
    webhook = argv[2]

token = 'token %s' % GITHUB_TOKEN
url = 'https://api.github.com/repos/%s/hooks' % repo
headers = {'Authorization': token}

response = requests.post(
    url,
    headers=headers,
    data=json.dumps({
        'name': 'web',
        'active': True,
        'events': ['*'],
        'config': {
            'url': webhook,
            'content_type': 'json',
        },
    })
)
print response, response.json()
