#!/usr/bin/env python

import os
import json
import time

import redis
import requests


SLACK_WEBHOOK = os.getenv('SLACK_WEBHOOK')

redis = redis.Redis()
pubsub = redis.pubsub()
pubsub.psubscribe('chatter*')


killed = False
while not killed:
    message = pubsub.get_message()

    if message and message['type'] == 'pmessage':
        text = message['data']
        try:
            payload = json.loads(text)
        except ValueError:
            payload = {
                'icon_emoji': ':redis:',
                'username': 'redis pubsub',
                'text': text,
            }
        response = requests.post(SLACK_WEBHOOK, data=json.dumps(payload))

    time.sleep(0.25)
